Repository go-generalize/volcago, pull requests merged in 2022-10, with the labels that each got.

#98 Update go mod
  go.mod
  go.sum
Labels: go

#99 ximを使ったコードが有効にならない #80
  examples/task.go
  examples/task_gen.go
  generator/structGenerator.go
Labels: bug, go

#104 string の Type alias に対応する
  examples/task.go
  examples/task_gen.go
  examples/task_label_gen.go
  generator/templates/gen.go.tmpl
  generator/testfiles/auto/task_gen.go
Labels: enhancement

#110 Fix call of reflect.Value.Type on zero Value
  examples/different_dir/misc_gen.go
  examples/misc_gen.go
  generator/templates/misc.go.tmpl
  generator/testfiles/auto/misc_gen.go
  generator/testfiles/misc/misc.go
  generator/testfiles/misc/misc_test.go
  generator/testfiles/not_auto/misc_gen.go
Labels: bug

#113 update: generated code
  examples/repository/misc_gen.go
Labels: go

#115 Support DocumentID in query #114
  examples/different_dir/lock_gen.go
  examples/history_gen.go
  examples/repository/task_gen.go
  examples/task_gen.go
  generator/funcMap.go
  generator/structGenerator.go
  generator/template.go
  generator/templates/gen.go.tmpl
  generator/testfiles/auto/lock_gen.go
  generator/testfiles/auto/task_gen.go
  generator/testfiles/auto/tests/model_test.go
  generator/testfiles/not_auto/sub_task_gen.go
  generator/testfiles/not_auto/task_gen.go
Labels: enhancement, go
